-- ============================================================
-- AIOS CLINICS - Schema completo (padrão multi-clínica)
-- Prefixo: aiosclinics_
-- Execute no SQL Editor do novo projeto Supabase
-- ============================================================

-- ============================================================
-- 1) AGENDAMENTOS
-- ============================================================
create table if not exists public.aiosclinics_agendamento (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Data" text,                         -- formato BR: dd/MM/yyyy HH:mm
  "Nome" text,
  "Número" text,
  "Anotações" text,
  "Confirmação" text,
  "1 Dia antes" text,
  "No dia" text,
  "Valor" numeric,
  "Responsavel_Agendamento" text,
  "Responsavel_Atendimento" text,
  "Tipo" text,
  "Procedimento" text
);

alter table public.aiosclinics_agendamento enable row level security;
create policy "public read agendamento"   on public.aiosclinics_agendamento for select using (true);
create policy "public insert agendamento" on public.aiosclinics_agendamento for insert with check (true);
create policy "public update agendamento" on public.aiosclinics_agendamento for update using (true);
create policy "public delete agendamento" on public.aiosclinics_agendamento for delete using (true);


-- ============================================================
-- 2) ANAMNESE
-- ============================================================
create table if not exists public.aiosclinics_anamnese (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  agendamento_id bigint references public.aiosclinics_agendamento(id) on delete set null,
  paciente_nome text,
  paciente_telefone text,
  data_anamnese date default current_date,
  queixa_principal text,
  historico_saude text,
  alergias text,
  medicamentos text,
  cirurgias_previas text,
  gestante boolean default false,
  procedimentos_anteriores text,
  tabagismo boolean default false,
  etilismo boolean default false,
  tipo_pele text,
  exposicao_solar text,
  observacoes text
);

alter table public.aiosclinics_anamnese enable row level security;
create policy "public read anamnese"   on public.aiosclinics_anamnese for select using (true);
create policy "public insert anamnese" on public.aiosclinics_anamnese for insert with check (true);
create policy "public update anamnese" on public.aiosclinics_anamnese for update using (true);
create policy "public delete anamnese" on public.aiosclinics_anamnese for delete using (true);


-- ============================================================
-- 3) ACOMPANHAMENTO
-- ============================================================
create table if not exists public.aiosclinics_acompanhamento (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  agendamento_id bigint references public.aiosclinics_agendamento(id) on delete set null,
  paciente_nome text,
  paciente_telefone text,
  data_inicio date default current_date,
  data_fim_tratamento date,
  status text default 'em_andamento',     -- em_andamento | finalizado | enviado
  observacoes text
);

alter table public.aiosclinics_acompanhamento enable row level security;
create policy "public read acomp"   on public.aiosclinics_acompanhamento for select using (true);
create policy "public insert acomp" on public.aiosclinics_acompanhamento for insert with check (true);
create policy "public update acomp" on public.aiosclinics_acompanhamento for update using (true);
create policy "public delete acomp" on public.aiosclinics_acompanhamento for delete using (true);


-- ============================================================
-- 4) FOTOS DO ACOMPANHAMENTO
-- ============================================================
create table if not exists public.aiosclinics_acompanhamento_fotos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  acompanhamento_id bigint not null references public.aiosclinics_acompanhamento(id) on delete cascade,
  foto_url text not null,
  foto_path text,
  data_foto date default current_date,
  ordem int default 0,
  nota text
);

alter table public.aiosclinics_acompanhamento_fotos enable row level security;
create policy "public read fotos"   on public.aiosclinics_acompanhamento_fotos for select using (true);
create policy "public insert fotos" on public.aiosclinics_acompanhamento_fotos for insert with check (true);
create policy "public update fotos" on public.aiosclinics_acompanhamento_fotos for update using (true);
create policy "public delete fotos" on public.aiosclinics_acompanhamento_fotos for delete using (true);


-- ============================================================
-- 5) RESPONSÁVEIS (agendamento / atendimento)
-- ============================================================
create table if not exists public.aiosclinics_responsaveis (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nome text not null,
  tipo text not null check (tipo in ('agendamento', 'atendimento')),
  ativo boolean default true,
  unique (nome, tipo)
);

alter table public.aiosclinics_responsaveis enable row level security;
create policy "public read responsaveis"   on public.aiosclinics_responsaveis for select using (true);
create policy "public insert responsaveis" on public.aiosclinics_responsaveis for insert with check (true);
create policy "public update responsaveis" on public.aiosclinics_responsaveis for update using (true);
create policy "public delete responsaveis" on public.aiosclinics_responsaveis for delete using (true);


-- ============================================================
-- 6) PROCEDIMENTOS (catálogo)
-- ============================================================
create table if not exists public.aiosclinics_procedimentos (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nome text not null unique,
  categoria text,           -- ex: facial, corporal, laser, injetável
  ativo boolean default true
);

alter table public.aiosclinics_procedimentos enable row level security;
create policy "public read procedimentos"   on public.aiosclinics_procedimentos for select using (true);
create policy "public insert procedimentos" on public.aiosclinics_procedimentos for insert with check (true);
create policy "public update procedimentos" on public.aiosclinics_procedimentos for update using (true);
create policy "public delete procedimentos" on public.aiosclinics_procedimentos for delete using (true);

-- Seed inicial do catálogo
insert into public.aiosclinics_procedimentos (nome, categoria) values
  ('Toxina botulínica', 'injetável'),
  ('Preenchimento com ácido hialurônico', 'injetável'),
  ('Harmonização facial', 'facial'),
  ('Bioestimulador de colágeno', 'injetável'),
  ('Hidroxiapatita de cálcio', 'injetável'),
  ('Skinbooster', 'injetável'),
  ('PRP (plasma rico em plaquetas)', 'injetável'),
  ('Mesoterapia', 'injetável'),
  ('Intradermoterapia', 'injetável'),
  ('Lipo enzimática', 'corporal'),
  ('Fios de sustentação (PDO)', 'facial'),
  ('Rinomodelação', 'facial'),
  ('Preenchimento labial', 'facial'),
  ('Microagulhamento', 'facial'),
  ('Microagulhamento com radiofrequência', 'facial'),
  ('Peeling químico', 'facial'),
  ('Peeling de diamante', 'facial'),
  ('Laser CO2 fracionado', 'laser'),
  ('Laser de picossegundos', 'laser'),
  ('Luz intensa pulsada (IPL)', 'laser'),
  ('Lavieen', 'laser'),
  ('Lifting facial não cirúrgico', 'facial'),
  ('Hidratação facial profunda', 'facial'),
  ('Depilação a laser', 'laser'),
  ('Criolipólise', 'corporal'),
  ('Radiofrequência corporal', 'corporal'),
  ('Drenagem linfática', 'corporal'),
  ('Massagem modeladora', 'corporal'),
  ('Carboxiterapia', 'corporal'),
  ('Lipocavitação', 'corporal'),
  ('Ultrassom focado corporal', 'corporal'),
  ('Endermologia (LPG)', 'corporal'),
  ('Vacuoterapia', 'corporal'),
  ('Pressoterapia', 'corporal'),
  ('Subcision para celulite', 'corporal'),
  ('Tratamento para estrias', 'corporal'),
  ('Bandagem modeladora', 'corporal'),
  ('Eletroestimulação muscular', 'corporal'),
  ('Hidrolipoclasia', 'corporal'),
  ('Argiloterapia', 'corporal')
on conflict (nome) do nothing;


-- ============================================================
-- 7) STORAGE BUCKET para fotos do acompanhamento
-- ============================================================
insert into storage.buckets (id, name, public)
values ('aiosclinics-acompanhamento-fotos', 'aiosclinics-acompanhamento-fotos', true)
on conflict (id) do nothing;

create policy "public read aios fotos"   on storage.objects for select using (bucket_id = 'aiosclinics-acompanhamento-fotos');
create policy "public upload aios fotos" on storage.objects for insert with check (bucket_id = 'aiosclinics-acompanhamento-fotos');
create policy "public update aios fotos" on storage.objects for update using (bucket_id = 'aiosclinics-acompanhamento-fotos');
create policy "public delete aios fotos" on storage.objects for delete using (bucket_id = 'aiosclinics-acompanhamento-fotos');
