-- ============================================================
-- Execute este SQL no SQL Editor do Supabase
-- Projeto: ehlpmukjdknnyhkycncb
-- Cria: Anamnese, Acompanhamento, Fotos + bucket público
-- ============================================================

create table if not exists public."Anamnese_DrColageno_Piracicaba" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  agendamento_id bigint references public."Agendamento_DrColageno_Piracicaba"(id) on delete set null,
  paciente_nome text,
  data_anamnese date default current_date,
  queixa_principal text,
  historico_saude text,
  alergias text,
  medicamentos text,
  cirurgias_previas text,
  gestante boolean default false,
  procedimentos_anteriores text,
  tabagismo boolean default false,
  etilismo boolean default false,
  tipo_pele text,
  exposicao_solar text,
  observacoes text
);

alter table public."Anamnese_DrColageno_Piracicaba" enable row level security;
create policy "public read anamnese"   on public."Anamnese_DrColageno_Piracicaba" for select using (true);
create policy "public insert anamnese" on public."Anamnese_DrColageno_Piracicaba" for insert with check (true);
create policy "public update anamnese" on public."Anamnese_DrColageno_Piracicaba" for update using (true);
create policy "public delete anamnese" on public."Anamnese_DrColageno_Piracicaba" for delete using (true);

create table if not exists public."Acompanhamento_DrColageno_Piracicaba" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  agendamento_id bigint references public."Agendamento_DrColageno_Piracicaba"(id) on delete set null,
  paciente_nome text,
  data_inicio date default current_date,
  data_fim_tratamento date,
  status text default 'em_andamento',
  observacoes text
);

alter table public."Acompanhamento_DrColageno_Piracicaba" enable row level security;
create policy "public read acomp"   on public."Acompanhamento_DrColageno_Piracicaba" for select using (true);
create policy "public insert acomp" on public."Acompanhamento_DrColageno_Piracicaba" for insert with check (true);
create policy "public update acomp" on public."Acompanhamento_DrColageno_Piracicaba" for update using (true);
create policy "public delete acomp" on public."Acompanhamento_DrColageno_Piracicaba" for delete using (true);

create table if not exists public."Acompanhamento_Fotos_DrColageno_Piracicaba" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  acompanhamento_id bigint not null references public."Acompanhamento_DrColageno_Piracicaba"(id) on delete cascade,
  foto_url text not null,
  foto_path text,
  data_foto date default current_date,
  ordem int default 0,
  nota text
);

alter table public."Acompanhamento_Fotos_DrColageno_Piracicaba" enable row level security;
create policy "public read fotos"   on public."Acompanhamento_Fotos_DrColageno_Piracicaba" for select using (true);
create policy "public insert fotos" on public."Acompanhamento_Fotos_DrColageno_Piracicaba" for insert with check (true);
create policy "public update fotos" on public."Acompanhamento_Fotos_DrColageno_Piracicaba" for update using (true);
create policy "public delete fotos" on public."Acompanhamento_Fotos_DrColageno_Piracicaba" for delete using (true);

insert into storage.buckets (id, name, public)
values ('acompanhamento-fotos', 'acompanhamento-fotos', true)
on conflict (id) do nothing;

create policy "public read acomp fotos"   on storage.objects for select using (bucket_id = 'acompanhamento-fotos');
create policy "public upload acomp fotos" on storage.objects for insert with check (bucket_id = 'acompanhamento-fotos');
create policy "public update acomp fotos" on storage.objects for update using (bucket_id = 'acompanhamento-fotos');
create policy "public delete acomp fotos" on storage.objects for delete using (bucket_id = 'acompanhamento-fotos');
