-- =============================================================================
-- AIOS CLINICS — Schema completo (padrão multi-clínica, naming universal)
-- =============================================================================
-- Como usar:
--   1. Crie um novo projeto Supabase para a clínica.
--   2. Abra o SQL Editor (ou rode via MCP `apply_migration`).
--   3. Cole este arquivo inteiro e execute. Idempotente — pode rodar 2x.
--   4. Pegue Project URL + publishable key e configure no app
--      (ver docs/CLONE_GUIDE.md).
--
-- Convenções:
--   - Prefixo `aiosclinics_` em todas as tabelas (multi-clínica friendly).
--   - RLS aberta (anon role) — todo acesso é via publishable key no client.
--     Quando adicionar auth, restrinja as policies por user_id/role.
--   - IDs bigint identity para tabelas operacionais (agenda/anamnese/acomp),
--     uuid para catálogos (responsaveis/procedimentos).
-- =============================================================================


-- =============================================================================
-- 1) AGENDAMENTOS
-- =============================================================================
create table if not exists public.aiosclinics_agendamento (
  id                       bigint generated by default as identity primary key,
  created_at               timestamptz not null default now(),
  "Data"                   text,           -- formato BR: "dd/MM/yyyy HH:mm"
  "Nome"                   text,
  "Número"                 text,
  "Anotações"              text,
  "Confirmação"            text,
  "1 Dia antes"            text,
  "No dia"                 text,
  "Valor"                  numeric,
  "Responsavel_Agendamento" text,
  "Responsavel_Atendimento" text,
  "Tipo"                   text,
  "Procedimento"           text
);

alter table public.aiosclinics_agendamento enable row level security;
create policy "public read agendamento"   on public.aiosclinics_agendamento for select using (true);
create policy "public insert agendamento" on public.aiosclinics_agendamento for insert with check (true);
create policy "public update agendamento" on public.aiosclinics_agendamento for update using (true);
create policy "public delete agendamento" on public.aiosclinics_agendamento for delete using (true);


-- =============================================================================
-- 2) ANAMNESE
-- =============================================================================
create table if not exists public.aiosclinics_anamnese (
  id                       bigint generated by default as identity primary key,
  created_at               timestamptz not null default now(),
  agendamento_id           bigint references public.aiosclinics_agendamento(id) on delete set null,
  paciente_nome            text,
  paciente_telefone        text,
  data_anamnese            date default current_date,
  queixa_principal         text,
  historico_saude          text,
  alergias                 text,
  medicamentos             text,
  cirurgias_previas        text,
  gestante                 boolean default false,
  procedimentos_anteriores text,
  tabagismo                boolean default false,
  etilismo                 boolean default false,
  tipo_pele                text,
  exposicao_solar          text,
  observacoes              text
);

alter table public.aiosclinics_anamnese enable row level security;
create policy "public read anamnese"   on public.aiosclinics_anamnese for select using (true);
create policy "public insert anamnese" on public.aiosclinics_anamnese for insert with check (true);
create policy "public update anamnese" on public.aiosclinics_anamnese for update using (true);
create policy "public delete anamnese" on public.aiosclinics_anamnese for delete using (true);


-- =============================================================================
-- 3) ACOMPANHAMENTO (evolução do paciente)
-- =============================================================================
create table if not exists public.aiosclinics_acompanhamento (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  agendamento_id      bigint references public.aiosclinics_agendamento(id) on delete set null,
  paciente_nome       text,
  paciente_telefone   text,
  data_inicio         date default current_date,
  data_fim_tratamento date,
  status              text default 'em_andamento',  -- em_andamento | finalizado | enviado
  observacoes         text
);

alter table public.aiosclinics_acompanhamento enable row level security;
create policy "public read acomp"   on public.aiosclinics_acompanhamento for select using (true);
create policy "public insert acomp" on public.aiosclinics_acompanhamento for insert with check (true);
create policy "public update acomp" on public.aiosclinics_acompanhamento for update using (true);
create policy "public delete acomp" on public.aiosclinics_acompanhamento for delete using (true);


-- =============================================================================
-- 4) FOTOS DO ACOMPANHAMENTO
-- =============================================================================
create table if not exists public.aiosclinics_acompanhamento_fotos (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz not null default now(),
  acompanhamento_id  bigint not null references public.aiosclinics_acompanhamento(id) on delete cascade,
  foto_url           text not null,
  foto_path          text,
  data_foto          date default current_date,
  ordem              int default 0,
  nota               text
);

alter table public.aiosclinics_acompanhamento_fotos enable row level security;
create policy "public read fotos"   on public.aiosclinics_acompanhamento_fotos for select using (true);
create policy "public insert fotos" on public.aiosclinics_acompanhamento_fotos for insert with check (true);
create policy "public update fotos" on public.aiosclinics_acompanhamento_fotos for update using (true);
create policy "public delete fotos" on public.aiosclinics_acompanhamento_fotos for delete using (true);


-- =============================================================================
-- 5) RESPONSÁVEIS (agendamento / atendimento)
-- =============================================================================
create table if not exists public.aiosclinics_responsaveis (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nome        text not null,
  tipo        text not null check (tipo in ('agendamento', 'atendimento')),
  ativo       boolean not null default true
);

-- Evita duplicidade case-insensitive de nome+tipo
create unique index if not exists aiosclinics_responsaveis_nome_tipo_unique
  on public.aiosclinics_responsaveis (lower(nome), tipo);

alter table public.aiosclinics_responsaveis enable row level security;
create policy "public read responsaveis"   on public.aiosclinics_responsaveis for select using (true);
create policy "public insert responsaveis" on public.aiosclinics_responsaveis for insert with check (true);
create policy "public update responsaveis" on public.aiosclinics_responsaveis for update using (true);
create policy "public delete responsaveis" on public.aiosclinics_responsaveis for delete using (true);


-- =============================================================================
-- 6) PROCEDIMENTOS (catálogo)
-- =============================================================================
create table if not exists public.aiosclinics_procedimentos (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nome        text not null unique,
  categoria   text,                            -- facial | corporal | laser | injetável
  ativo       boolean not null default true,
  ordem       integer not null default 0
);

alter table public.aiosclinics_procedimentos enable row level security;
create policy "public read procedimentos"   on public.aiosclinics_procedimentos for select using (true);
create policy "public insert procedimentos" on public.aiosclinics_procedimentos for insert with check (true);
create policy "public update procedimentos" on public.aiosclinics_procedimentos for update using (true);
create policy "public delete procedimentos" on public.aiosclinics_procedimentos for delete using (true);

-- Seed do catálogo padrão (50 procedimentos estéticos)
insert into public.aiosclinics_procedimentos (nome, categoria, ordem) values
  ('Toxina botulínica',                       'injetável', 1),
  ('Preenchimento com ácido hialurônico',     'injetável', 2),
  ('Harmonização facial',                     'facial',    3),
  ('Bioestimulador de colágeno',              'injetável', 4),
  ('Hidroxiapatita de cálcio',                'injetável', 5),
  ('Skinbooster',                             'injetável', 6),
  ('PRP (plasma rico em plaquetas)',          'injetável', 7),
  ('Mesoterapia',                             'injetável', 8),
  ('Intradermoterapia',                       'injetável', 9),
  ('Lipo enzimática',                         'corporal',  10),
  ('Fios de sustentação (PDO)',               'facial',    11),
  ('Rinomodelação',                           'facial',    12),
  ('Preenchimento labial',                    'facial',    13),
  ('Microagulhamento',                        'facial',    14),
  ('Microagulhamento com radiofrequência',    'facial',    15),
  ('Drug delivery',                           'facial',    16),
  ('Peeling químico',                         'facial',    17),
  ('Peeling de diamante',                     'facial',    18),
  ('Peeling de cristal',                      'facial',    19),
  ('Microdermoabrasão',                       'facial',    20),
  ('Limpeza de pele',                         'facial',    21),
  ('Luz intensa pulsada',                     'laser',     22),
  ('Fotorejuvenescimento',                    'laser',     23),
  ('Ultrassom microfocado (HIFU)',            'facial',    24),
  ('Radiofrequência facial',                  'facial',    25),
  ('Criofrequência facial',                   'facial',    26),
  ('Jato de plasma',                          'facial',    27),
  ('LED terapia',                             'facial',    28),
  ('Laser fracionado',                        'laser',     29),
  ('Laser de picossegundos',                  'laser',     30),
  ('Lavieen',                                 'laser',     31),
  ('Lifting facial não cirúrgico',            'facial',    32),
  ('Hidratação facial profunda',              'facial',    33),
  ('Depilação a laser',                       'laser',     34),
  ('Criolipólise',                            'corporal',  35),
  ('Radiofrequência corporal',                'corporal',  36),
  ('Drenagem linfática',                      'corporal',  37),
  ('Massagem modeladora',                     'corporal',  38),
  ('Carboxiterapia',                          'corporal',  39),
  ('Lipocavitação',                           'corporal',  40),
  ('Ultrassom focado corporal',               'corporal',  41),
  ('Endermologia (LPG)',                      'corporal',  42),
  ('Vacuoterapia',                            'corporal',  43),
  ('Pressoterapia',                           'corporal',  44),
  ('Subcision para celulite',                 'corporal',  45),
  ('Tratamento para estrias',                 'corporal',  46),
  ('Bandagem modeladora',                     'corporal',  47),
  ('Eletroestimulação muscular',              'corporal',  48),
  ('Hidrolipoclasia',                         'corporal',  49),
  ('Argiloterapia',                           'corporal',  50)
on conflict (nome) do nothing;


-- =============================================================================
-- 7) STORAGE BUCKET — fotos do acompanhamento
-- =============================================================================
insert into storage.buckets (id, name, public)
values ('aiosclinics-acompanhamento-fotos', 'aiosclinics-acompanhamento-fotos', true)
on conflict (id) do nothing;

-- Policies do bucket (executam contra storage.objects)
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='public read aios fotos') then
    create policy "public read aios fotos"   on storage.objects for select using (bucket_id = 'aiosclinics-acompanhamento-fotos');
  end if;
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='public upload aios fotos') then
    create policy "public upload aios fotos" on storage.objects for insert with check (bucket_id = 'aiosclinics-acompanhamento-fotos');
  end if;
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='public update aios fotos') then
    create policy "public update aios fotos" on storage.objects for update using (bucket_id = 'aiosclinics-acompanhamento-fotos');
  end if;
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='public delete aios fotos') then
    create policy "public delete aios fotos" on storage.objects for delete using (bucket_id = 'aiosclinics-acompanhamento-fotos');
  end if;
end$$;


-- =============================================================================
-- 8) VALIDAÇÃO RÁPIDA
-- =============================================================================
-- Rode após o setup. Deve retornar 6 tabelas, 1 bucket e >= 50 procedimentos.
--
--   select count(*) as tables   from information_schema.tables
--     where table_schema='public' and table_name like 'aiosclinics_%';
--
--   select count(*) as buckets  from storage.buckets where id='aiosclinics-acompanhamento-fotos';
--
--   select count(*) as procs    from public.aiosclinics_procedimentos;
